### ISSUE TITLE
starter 支持

### ISSUE THREAD

**Issue by chenshun00** [hengyunabc/spring-boot-utils#2]
加入我一个starter既要支持1.5也要支持2.0的，有没有什么好的处理方法呢，目的是为了加载自定义路径下的 `jsp` ，代码如下

```
    @Bean  
    @ConditionalOnProperty(name = "tomcat.staticResourceCustomizer.enabled", matchIfMissing = true)
    public EmbeddedServletContainerCustomizer staticResourceCustomizer() {
        return container -> {
            if (container instanceof TomcatEmbeddedServletContainerFactory) {
                ((TomcatEmbeddedServletContainerFactory) container)
                        .addContextCustomizers((TomcatContextCustomizer) context
                                -> context.addLifecycleListener(new ResourceConfigurer(context)));
            }
        };
}
```
这里是1的，但是 `EmbeddedServletContainerCustomizer` 在2变成 `TomcatServletWebServerFactory` 了，实际测试发现返回 `Object` 是行不通的，会出现404. 
不知道您有什么好的建议，目前我是单独做了2个starter，但是不太好维护，使用上也不太方便。

**Comment by hengyunabc** [comment]
用 `@ConditionalOnClass` 判断下，写两个`@Configuration`。参考工程里的代码。

**Comment by chenshun00** [comment]
@hengyunabc 👌，我试下，但是`@Bean` 注解的处理类型必须是一个明确的 `Class` (Object 是不行的)，不然配置的 `bean` 我们就获取不到了.

**Comment by chenshun00** [comment]
@hengyunabc 还是有问题的，我们这种使用的格式，因为要使用到@Bean到返回值.

```java
    @Bean   
    public EmbeddedServletContainerCustomizer staticResourceCustomizer() {}
```

```java
this.beanFactory.getBeansOfType(EmbeddedServletContainerCustomizer.class,false, false)
```

按照你到那种运行时获取不能解决这个 `EmbeddedServletContainerCustomizer` 返回值的问题，如果将返回值写成object，那Spring就获取不到它了，范型也会被差除，好像基本上无解了.

**Comment by hengyunabc** [comment]
> @hengyunabc 还是有问题的，我们这种使用的格式，因为要使用到@bean到返回值.
> 
> ```java
>     @Bean   
>     public EmbeddedServletContainerCustomizer staticResourceCustomizer() {}
> ```
> 
> ```java
> this.beanFactory.getBeansOfType(EmbeddedServletContainerCustomizer.class,false, false)
> ```
> 
> 按照你到那种运行时获取不能解决这个 `EmbeddedServletContainerCustomizer` 返回值的问题，如果将返回值写成object，那Spring就获取不到它了，范型也会被差除，好像基本上无解了.

我的意思是，分两个模块，不同的模块判断是否spring boo1/2，然后分别设置tomcat。并不需要返回 Object。

**Comment by hengyunabc** [comment]
参考这个： http://hengyunabc.github.io/spring-boot-starter-compatibility/

**Comment by chenshun00** [comment]
不好意思，再次打扰下，大致看了一下，写了个demo，一开始的意思是我写2个 module , 都加载进去，利用SpringBoot 1和2 自身的特性去做这个事？

**Comment by hengyunabc** [comment]
> 不好意思，再次打扰下，大致看了一下，写了个demo，一开始的意思是我写2个 module , 都加载进去，利用SpringBoot 1和2 自身的特性去做这个事？

。。文章写得很清楚了，并且有demo。自己导入IDE里跑下。
